name: Invitation to Odisha Students Code Community (OSCC)
description: Request an invitation to join the official OSCC GitHub Organization
title: "Please invite me to the Odisha Students Code Community Organization"
labels: [invite me to the community]
body:
  - type: input
    id: name
    attributes:
      label: Name / Nickname
      placeholder: Enter your name
    validations:
      required: true
  - type: input
    id: college
    attributes:
      label: College / Institution
      placeholder: e.g. OUTR, VSSUT, CET, Ravenshaw, Polytechnic, etc.
    validations:
      required: false
  - type: textarea
    id: interests
    attributes:
      label: What are your technical interests?
      placeholder: e.g. Web development, Python, Git, UI/UX, AI, Mobile apps
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Welcome to **Odisha Students Code Community (OSCC)** ❤️! 
        Once you submit this issue, our bot will automatically dispatch an invitation to your GitHub account and close this issue.
